AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda with Express

Resources:

  tmapp:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: tmapp/tmapp.handler
      CodeUri: ./Lambda
      Runtime: nodejs10.x
      AutoPublishAlias: live
      Description: 'Lambda function for CD Demo with express'
      MemorySize: 128
      Timeout: 30
      DeploymentPreference:
          Type: Linear10PercentEvery1Minute
          Alarms:
            - !Ref AliasErrorMetricGreaterThanZeroAlarm
            - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
          # Hooks:
          #   PreTraffic: !Ref PreTrafficHook
          #   PostTraffic: !Ref PostTrafficHook
      Events:
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
      Environment:
        Variables:
          REGION: ap-south-1
          
  AliasErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${tmapp}:live"
        - Name: FunctionName
          Value: !Ref tmapp
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  LatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${tmapp}:live"
        - Name: FunctionName
          Value: !Ref tmapp
        - Name: ExecutedVersion
          Value: !GetAtt tmapp.Version.Version
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0


  # PreTrafficHook:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: preTrafficHook.handler
  #     Runtime: nodejs10.x
  #     CodeUri: ./Lambda
  #     FunctionName: 'CodeDeployHook_PreTrafficHook'
  #     Policies:
  #       - Version: "2012-10-17"
  #         Statement: 
  #         - Effect: "Allow"
  #           Action: 
  #             - "codedeploy:PutLifecycleEventHookExecutionStatus"
  #           Resource:
  #             !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
  #       - Version: "2012-10-17"
  #         Statement: 
  #         - Effect: "Allow"
  #           Action: 
  #             - "lambda:InvokeFunction"
  #           Resource: !Ref HelloWorld.Version
  #     DeploymentPreference:
  #       Enabled: false
  #     Timeout: 5
  #     Environment:
  #       Variables:
  #         NewVersion: !Ref HelloWorld.Version

  # PostTrafficHook:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: postTrafficHook.handler
  #     Runtime: nodejs10.x
  #     CodeUri: ./Lambda
  #     FunctionName: 'CodeDeployHook_PostTrafficHook'
  #     Policies:
  #       - Version: "2012-10-17"
  #         Statement: 
  #         - Effect: "Allow"
  #           Action: 
  #             - "codedeploy:PutLifecycleEventHookExecutionStatus"
  #           Resource:
  #             !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
  #       - Version: "2012-10-17"
  #         Statement: 
  #         - Effect: "Allow"
  #           Action: 
  #             - "lambda:InvokeFunction"
  #           Resource: !Ref HelloWorld.Version
  #     DeploymentPreference:
  #       Enabled: false
  #     Timeout: 5
  #     Environment:
  #       Variables:
  #         NewVersion: !Ref HelloWorld.Version